lib/tech_from_scratch_web/router.ex
defmodule TechFromScratchWeb.Router do
  use TechFromScratchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TechFromScratchWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/annotations", AnnotationsController, :index
    get "/projects", ProjectsController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TechFromScratchWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TechFromScratchWeb.Telemetry
    end
  end
end

lib/tech_from_scratch/annotations.ex
defmodule TechFromScratch.Annotations do
  defstruct [:name, :thumbnail, :docs_link, :views]
  alias TechFromScratch.Annotations

  def list_annotations() do
    [
      %Annotations{
        name: "Elixir in Action",
        thumbnail: "/images/annotations/elixir-in-action.jpg",
        docs_link: "/annotations/elixir-in-action/index.html",
        views: 18
      },
      %Annotations{
        name: "Programming Phoenix",
        thumbnail: "/images/annotations/programming-phoenix.jpg",
        docs_link: "/annotations/programming-phoenix/index.html",
        views: 134
      }
    ]
  end

  def list_annotations(offset, amount) do
    list_annotations()
    |> Enum.slice(offset, amount)
  end
end

lib/tech_from_scratch/application.ex
defmodule TechFromScratch.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      TechFromScratch.Repo,
      # Start the Telemetry supervisor
      TechFromScratchWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: TechFromScratch.PubSub},
      # Start the Endpoint (http/https)
      TechFromScratchWeb.Endpoint
      # Start a worker by calling: TechFromScratch.Worker.start_link(arg)
      # {TechFromScratch.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TechFromScratch.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TechFromScratchWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/tech_from_scratch/projects.ex
defmodule TechFromScratch.Projects do
  defstruct [:name, :icon, :docs_link, :views, :description, :code_link]
  alias TechFromScratch.Projects

  def list_projects() do
    [
      %Projects{
        name: "Banking Prototype",
        icon: "fas fa-hand-holding-usd",
        code_link: "https://github.com/oliveigah/banking-prototype",
        views: 123,
        description: "System that manage financial accounts and currency transfers.",
        docs_link: "/projects/banking-prototype/index.html"
      },
      %Projects{
        name: "Distributed Logger",
        icon: "fas fa-share-alt-square",
        docs_link: "/projects/distributed-logger/index.html",
        views: 32,
        description: "System that handle log distribution among multiple servers.",
        code_link: "https://github.com/oliveigah/distributed-logger"
      },
      %Projects{
        name: "Tech From Scratch",
        icon: "fas fa-file-import",
        docs_link: "/",
        views: 221,
        description: "Personal blog written in elixir using phoenix framework",
        code_link: "https://github.com/oliveigah/tech-from-scratch"
      }
    ]
  end

  def list_projects(offset, amount) do
    list_projects()
    |> Enum.slice(offset, amount)
  end
end

lib/tech_from_scratch/repo.ex
defmodule TechFromScratch.Repo do
  use Ecto.Repo,
    otp_app: :tech_from_scratch,
    adapter: Ecto.Adapters.Postgres
end

lib/tech_from_scratch_web/controllers/annotations_controller.ex
defmodule TechFromScratchWeb.AnnotationsController do
  use TechFromScratchWeb, :controller

  def get_layout_params() do
    [
      header_image: "/images/annotations-bg.jpg",
      header_title: "Annotations",
      header_subtitle: "while (true) do: learn( )"
    ]
  end

  def index(conn, _params) do
    annotations = TechFromScratch.Annotations.list_annotations()
    params = [annotations: annotations] ++ get_layout_params()
    render(conn, "index.html", params)
  end
end

lib/tech_from_scratch_web/controllers/home_controller.ex
defmodule TechFromScratchWeb.HomeController do
  use TechFromScratchWeb, :controller

  def get_layout_params() do
    [
      header_image: "/images/home-bg.jpg",
      header_title: "Tech From Scratch",
      header_subtitle: "A personal journey: from concept to practice"
    ]
  end

  def index(conn, _params) do
    render(conn, "index.html", get_layout_params())
  end
end

lib/tech_from_scratch_web/controllers/projects_controller.ex
defmodule TechFromScratchWeb.ProjectsController do
  use TechFromScratchWeb, :controller

  def get_layout_params() do
    [
      header_image: "/images/projects-bg.jpg",
      header_title: "Projects",
      header_subtitle: "theory |> practice( )"
    ]
  end

  def index(conn, _params) do
    projects = TechFromScratch.Projects.list_projects()
    params = [projects: projects] ++ get_layout_params()
    render(conn, "index.html", params)
  end
end

lib/tech_from_scratch_web/views/error_view.ex
defmodule TechFromScratchWeb.ErrorView do
  use TechFromScratchWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/tech_from_scratch_web/views/home_view.ex
defmodule TechFromScratchWeb.HomeView do
  use TechFromScratchWeb, :view
end

lib/tech_from_scratch_web/views/layout_view.ex
defmodule TechFromScratchWeb.LayoutView do
  use TechFromScratchWeb, :view
end

lib/tech_from_scratch_web/templates/annotations/index.html.eex
<div class="container">
  <div class="row">
  <%= for annotation <- @annotations do%>
    <div class="col-md-4">
      <div class="card mb-4 box-shadow annotations-thumbnail">
        <img class="card-img-top" src="<%= Routes.static_path(@conn, annotation.thumbnail) %>" data-holder-rendered="true">
      </div>
      <div>
          <div class="d-flex justify-content-center align-items-center">
            <h4> <%= annotation.name %></h4>
          </div>
          <div class="d-flex justify-content-center align-items-center">
            <small class="text-muted fas fa-eye"> <%=annotation.views%> </small>
          </div>
          </br>
          <div class="d-flex justify-content-center align-items-center">
            <div class="btn-group">
              <a href="<%= Routes.static_path(@conn, annotation.docs_link) %>" type="button" class="btn btn-sm btn-outline-secondary">View Notes</a>
            </div>
          </div>
      </div>
      </br>
    </div>
  <% end %>
  </div>
</div>

lib/tech_from_scratch_web/templates/home/index.html.eex
<div class="d-flex justify-content-center align-items-center">
  <h1> WORK IN PROGRESS</h1>
</div>

lib/tech_from_scratch_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TFS | Home</title>
      <!-- Custom fonts for this template -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="<%= Routes.home_path(@conn, :index) %>">Tech From Scratch</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= Routes.home_path(@conn, :index)%>"> Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=Routes.projects_path(@conn, :index)%>">Projects</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="<%=Routes.annotations_path(@conn, :index)%>">Annotations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead" style="background-image: url(<%= Routes.static_path(@conn, @header_image) %>)">
      <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-10 col-md-10 mx-auto">
              <div class="site-heading">
                <h1><%= @header_title %></h1>
                <span class="subheading"><%= @header_subtitle%></span>
              </div>
            </div>
          </div>
      </div>
    </header>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>

  <hr>

     <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/oliveigah">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/oliveigah">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="mailto:oliveira.gahenrique@gmail.com">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fas fa-envelope fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyleft 🄯 | Tech From Scratch 2021</p>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>

lib/tech_from_scratch_web/templates/projects/index.html.eex
<div class="container">
  <div class="row">
  <%= for project <- @projects do%>
    <div class="col-md-4">
      <div class="d-flex justify-content-center align-items-center">
        <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="<%= project.icon %> fa-stack-1x fa-inverse"></i>
        </span>
      </div>
      </br>
      <div>
          <div class="d-flex justify-content-center align-items-center">
            <h4> <%= project.name %></h4>
          </div>

          <div class="card-body">
                  <p class="card-text" style="text-align: center; min-height: 100px"><%= project.description%></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="<%= Routes.static_path(@conn, project.docs_link) %>" type="button" class="btn btn-sm btn-outline-secondary">Docs</a>
                      <a href="<%=project.code_link%>" type="button" class="btn btn-sm btn-outline-secondary">Github</a>
                    </div>
                    <small class="text-muted fas fa-eye"> <%=project.views%> </small>
                  </div>
          </div>
      </div>
      </br>
    </div>
  <% end %>
  </div>
</div>